navbarLinks:
    Home: /
    Github: https://github.com/madnight
    RSS: /atom.xml
    About: /about/

favicon: /fav.png

header:
    title: "beuke.org"
    motto: "A personal blog about technical topics."

rss: /atom.xml

footer:
  github:
    link: 'https://github.com/madnight'
    title: GitHub
    icon: fa-github
    enable: true
  rss:
    link: '/atom.xml'
    title: RSS
    icon: fa-rss
    enable: true
  mail:
    link: 'mailto:mail@beuke.org'
    title: Email me
    icon: fa-envelope
    enable: true
  stackoverflow:
    link: 'https://stackoverflow.com/users/6593641/madnight'
    title: StackOverflow
    icon: fa-stack-overflow
    enable: true

comment:
  enable: true
  disqus: beuke
  disqus_shortname: beuke
